#端口
server:
  port: 8001
#服务名称
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//192.168.119.130:1521/orcl
    username: hongwu
    password: hongwu

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.atguigu.springcloud.entities

#配置Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka/
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    #修改注册eureka上的主机名称
    instance-id: payment8001
    #开启ip显示,这个功能需要加载actuator包
    prefer-ip-address: true